export const letras = [
    {content: 'A', id: 'letterA'},
    {content: 'B', id: 'letterB'},
    {content: 'C', id: 'letterC'},
    {content: 'D', id: 'letterD'},
    {content: 'E', id: 'letterE'},
    {content: 'F', id: 'letterF'},
    {content: 'G', id: 'letterG'},
    {content: 'H', id: 'letterH'},
    {content: 'I', id: 'letterI'},
    {content: 'J', id: 'letterJ'},
    {content: 'K', id: 'letterK'},
    {content: 'L', id: 'letterL'},
    {content: 'M', id: 'letterM'},
    {content: 'N', id: 'letterN'},
    {content: 'O', id: 'letterO'},
    {content: 'P', id: 'letterP'},
    {content: 'Q', id: 'letterQ'},
    {content: 'R', id: 'letterR'},
    {content: 'S', id: 'letterS'},
    {content: 'T', id: 'letterT'},
    {content: 'U', id: 'letterU'},
    {content: 'V', id: 'letterV'},
    {content: 'W', id: 'letterW'},
    {content: 'X', id: 'letterX'},
    {content: 'Y', id: 'letterY'},
    {content: 'Z', id: 'letterZ'}
];
